/** @format */
"use client";
import React from "react";
import "./globals.css";
import { Inter } from "next/font/google";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import {
  UploadOutlined,
  UserOutlined,
  VideoCameraOutlined,
} from "@ant-design/icons";
import { Layout, Menu, theme, ConfigProvider } from "antd";
import AppHeader from "@/components/AppHeader";
import Navbar from "@/components/navbar";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const { Header, Content, Footer, Sider } = Layout;

const items = [
  UserOutlined,
  VideoCameraOutlined,
  UploadOutlined,
  UserOutlined,
].map((icon, index) => ({
  key: String(index + 1),
  icon: React.createElement(icon),
  label: `nav ${index + 1}`,
}));

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      //  className={inter.className}
      >
        <AntdRegistry>
          <ConfigProvider
            theme={{
              algorithm: theme.defaultAlgorithm,
            }}
          >
            <Layout style={{ height: "100vh", overflow: "hidden" }}>
              <Header
                style={{ padding: 0, background: "blue", color: "white" }}
              >
                <AppHeader />
              </Header>
              <Layout>
                <Sider
                  breakpoint="lg"
                  collapsedWidth="0"
                  onBreakpoint={(broken) => {
                    console.log(broken);
                  }}
                  onCollapse={(collapsed, type) => {
                    console.log(collapsed, type);
                  }}
                  style={{ overflowY: "hidden" }}
                >
                  <div className="demo-logo-vertical" />
                  {/* <Menu
                    theme="dark"
                    mode="inline"
                    defaultSelectedKeys={["4"]}
                    items={items}
                  /> */}
                  <Navbar />
                </Sider>
                <Content
                // style={{ margin: "24px 16px 0" }}
                >
                  <div
                    style={{
                      padding: 24,
                      // minHeight: 360,
                      background: "white",
                      // borderRadius: 30,
                    }}
                  >
                    {children}
                  </div>
                </Content>
                <Sider width="10%" style={{ backgroundColor: "#4096ff" }}>
                  Sider
                </Sider>
              </Layout>
            </Layout>
          </ConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
