/** @format */
"use client";
import React, { useEffect, useState } from "react";
import "./globals.css";
import { Inter } from "next/font/google";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import {
  UploadOutlined,
  UserOutlined,
  VideoCameraOutlined,
} from "@ant-design/icons";
import { Layout, theme, ConfigProvider } from "antd";
import AppHeader from "@/components/AppHeader";
import Navbar from "@/components/navbar";
import { usePathname } from "next/navigation";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const { Header, Content, Sider } = Layout;

export default function RootLayout({ children }) {
  const [sidebar, showSidebar] = useState(false);
  const path = usePathname(); // This only works on the client-side

  useEffect(() => {
    path === "/editor" ? showSidebar(true) : showSidebar(false);
  }, [path]);

  return (
    <html lang="en">
      <body
      //  className={inter.className}
      >
        <AntdRegistry>
          <ConfigProvider
            theme={{
              algorithm: theme.defaultAlgorithm,
            }}
          >
            <Layout style={{ height: "100vh", overflow: "hidden" }}>
              <Header
                style={{ padding: 0, background: "blue", color: "white" }}
              >
                <AppHeader />
              </Header>
              <Layout>
                <Sider
                  breakpoint="lg"
                  collapsedWidth="0"
                  onBreakpoint={(broken) => {
                    console.log(broken);
                  }}
                  onCollapse={(collapsed, type) => {
                    console.log(collapsed, type);
                  }}
                  style={{ overflowY: "hidden" }}
                >
                  <div className="demo-logo-vertical" />
                  <Navbar />
                </Sider>
                <Content
                // style={{ margin: "24px 16px 0" }}
                >
                  <div
                    style={{
                      padding: 24,
                      // minHeight: 360,
                      background: "white",
                      // borderRadius: 30,
                    }}
                  >
                    {children}
                  </div>
                </Content>
                {sidebar && (
                  <Sider width="10%" style={{ backgroundColor: "#4096ff" }}>
                    Sider
                  </Sider>
                )}
              </Layout>
            </Layout>
          </ConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
