/** @format */
"use client";
import React, { useEffect, useState } from "react";
import "./globals.css";
// import { Inter } from "next/font/google";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import {
  UploadOutlined,
  UserOutlined,
  VideoCameraOutlined,
} from "@ant-design/icons";
import { Layout, theme, ConfigProvider, Menu } from "antd";
import AppHeader from "@/components/AppHeader";
import Navbar from "@/components/navbar";
import { usePathname } from "next/navigation";
import { Provider } from "react-redux";
import { store } from "../utils/store";
import ToolBar from "@/components/toolBar";
import Head from "next/head"; // Import Head from Next.js

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const { Header, Content, Sider } = Layout;

export default function RootLayout({ children }) {
  const [sidebar, showSidebar] = useState(false);
  const path = usePathname();
  const [userTheme, setUserTheme] = useState("light");
  const [node, clickedNode] = useState();

  const handleThemeChange = (newTheme) => {
    console.log(newTheme);
    setUserTheme(newTheme);
    return;
  };

  const addNode = (node) => {
    console.log(node);
    clickedNode(node);
    return;
  };

  useEffect(() => {
    path === "/editor" ? showSidebar(true) : showSidebar(false);
  }, [path]);

  const Pages = React.cloneElement(children, { userTheme, node });

  const items = [
    UserOutlined,
    VideoCameraOutlined,
    UploadOutlined,
    UserOutlined,
  ].map((icon, index) => ({
    key: String(index + 1),
    icon: React.createElement(icon),
    label: `nav ${index + 1}`,
  }));

  return (
    <html lang="en">
      <Head>
        {/* General SEO */}
        <title>Your App Title</title>
        <meta name="description" content="Your app description here." />
        <meta name="keywords" content="your, app, keywords, here" />

        {/* Open Graph / Facebook */}
        <meta property="og:image" content="Link preview image URL" />
        <meta property="og:site_name" content="Link preview site name" />
        <meta property="og:title" content="Link preview title" />
        <meta property="og:description" content="Link preview description" />
        <meta property="og:url" content="Link preview URL" />

        <meta property="og:type" content="website" />
        <meta
          property="og:url"
          content="https://ivr-platform.vercel.app/editor"
        />
        <meta property="og:title" content="Your App Title" />
        <meta property="og:description" content="Your app description here." />
        <meta
          property="og:image"
          content="https://yourwebsite.com/og-image.jpg"
        />

        {/* Twitter */}

        {/* <meta property="twitter:image" content="Twitter link preview image URL"/>
        <meta property="twitter:card" content="summary_large_image"/>
        <meta property="twitter:title" content="Twitter link preview title" />
        <meta property="twitter:description" content="Twitter link preview description" />
        <meta property="description" content="Search engine description" /> */}

        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:url" content="https://yourwebsite.com/" />
        <meta name="twitter:title" content="Your App Title" />
        <meta name="twitter:description" content="Your app description here." />
        <meta
          name="twitter:image"
          content="https://yourwebsite.com/twitter-image.jpg"
        />
      </Head>
      <body>
        <AntdRegistry>
          <ConfigProvider
            theme={{
              algorithm:
                userTheme === "light"
                  ? theme.defaultAlgorithm
                  : theme.darkAlgorithm,
              token: {
                colorPrimary: "#1890ff", // Default primary blue color for light theme
                colorPrimaryDark: "#001529", // Default primary dark color
              },
            }}
          >
            <Layout style={{ height: "100vh", overflow: "hidden" }}>
              <Header
                style={{
                  padding: 0,
                  // background: "white",
                  color: "white",
                }}
              >
                <AppHeader onThemeChange={handleThemeChange} />
              </Header>
              <Layout>
                <Sider
                  breakpoint="lg"
                  collapsedWidth="0"
                  onBreakpoint={(broken) => {
                    console.log(broken);
                  }}
                  onCollapse={(collapsed, type) => {
                    console.log(collapsed, type);
                  }}
                  style={{ overflowY: "hidden" }}
                >
                  <div className="demo-logo-vertical" />
                  {/* <Menu
                    theme="dark"
                    mode="inline"
                    defaultSelectedKeys={["4"]}
                    items={items}
                  /> */}
                  <Navbar />
                </Sider>
                <Content
                  style={{
                    // margin: "24px 16px 0",
                    overflowY: "auto",
                    // minHeight: "100vh",
                    height: "100vh",
                  }}
                >
                  <div
                    style={{
                      padding: 15,
                      // minHeight: 360,
                      // background: "white",
                      // borderRadius: 30,
                    }}
                  >
                    <Provider store={store}>{Pages}</Provider>
                  </div>
                </Content>
                {sidebar && (
                  <Provider store={store}>
                    <Sider width="10%" style={{ backgroundColor: "#4096ff" }}>
                      <ToolBar addNode={addNode} />
                    </Sider>
                  </Provider>
                )}
              </Layout>
            </Layout>
          </ConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
